name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pdf-manager:${{ github.sha }}
    
    - name: Tag latest image
      run: docker tag pdf-manager:${{ github.sha }} pdf-manager:latest
    
    - name: List Docker images
      run: docker images | grep pdf-manager