# Workflow for Docker Image

name: Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t rahul1231/pdf-manager .

      - name: Push Docker image
        run: |
          docker push rahul1231/pdf-manager